# Generated by Django 6.0.4 on 2026-05-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0008_doctor_is_active_paciente_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
