# Generated by Django 6.0.4 on 2026-05-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0007_alter_medicamento_imagen'),
        ('clinix', '0008_doctor_is_active_paciente_is_active_and_more'),
    ]

    operations = [
    ]
