# Generated by Django 6.0.4 on 2026-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0009_merge_20260516_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientomedicamento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
