# Generated by Django 6.0.4 on 2026-05-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0010_add_fecha_fin_to_tratamientomedicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientomedicamento',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='tratamientomedicamento',
            name='duracion_dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
