# Generated by Django 6.0.4 on 2026-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0011_replace_fecha_fin_with_duracion_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientetratamiento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
