# Generated by Django 6.0.4 on 2026-05-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinix', '0009_alter_medicamento_imagen'),
        ('clinix', '0012_add_fecha_inicio_to_pacientetratamiento'),
    ]

    operations = [
    ]
